# Generated by Django 3.0.5 on 2020-04-04 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0002_auto_20200404_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
