# Generated by Django 3.0.5 on 2020-04-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0003_game_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='group_finder.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(to='group_finder.Account'),
        ),
    ]
