# Generated by Django 3.0.5 on 2020-04-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0004_auto_20200404_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creation_date',
        ),
    ]
