# Generated by Django 3.0.5 on 2020-04-05 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0005_remove_game_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
