# Generated by Django 3.0.5 on 2020-04-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0006_game_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
