# Generated by Django 3.0.5 on 2020-04-14 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_finder', '0008_game_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='dnd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
