# Generated by Django 3.0.5 on 2020-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0009_auto_20200414_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='accepting_players',
            field=models.BooleanField(default=True),
        ),
    ]
