# Generated by Django 3.0.5 on 2020-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0010_game_accepting_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='class_text',
            field=models.CharField(default='swag', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='race_text',
            field=models.CharField(default='dgfhgdf', max_length=30),
            preserve_default=False,
        ),
    ]
