# Generated by Django 3.0.5 on 2020-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0011_auto_20200415_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_text',
            field=models.CharField(max_length=30, verbose_name='Character Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name_text',
            field=models.CharField(max_length=50, verbose_name='Character Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_text',
            field=models.CharField(max_length=30, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race_text',
            field=models.CharField(max_length=30, verbose_name='Character Race'),
        ),
        migrations.AlterField(
            model_name='game',
            name='campaign_text',
            field=models.CharField(max_length=200, verbose_name='Campaign Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_text',
            field=models.CharField(max_length=200, verbose_name='Game Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(max_length=100, verbose_name='Game'),
        ),
    ]
