# Generated by Django 3.0.5 on 2020-04-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0014_auto_20200416_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='accepting_players',
        ),
    ]
