# Generated by Django 3.0.5 on 2020-04-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_finder', '0016_game_accepting_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='accepting_players',
            field=models.BooleanField(default=True),
        ),
    ]
